mongodb-js/compass-aggregations

package-lock.json, package.json
Updated mongodb-stage-validator 0.0.3 version with fix of validation with regex
=> COMPASS-2887 Agg pipeline updated validation

package-lock.json, package.json, src/components/aggregations/aggregations.jsx, src/components/pipeline-builder-toolbar/pipeline-builder-toolbar.less, src/components/pipeline-preview-toolbar/pipeline-preview-toolbar.jsx, src/components/pipeline-preview-toolbar/pipeline-preview-toolbar.less, src/components/pipeline-preview-toolbar/pipeline-preview-toolbar.spec.js, src/components/pipeline-toolbar/pipeline-toolbar.jsx, src/components/pipeline-toolbar/pipeline-toolbar.spec.js, src/components/pipeline-workspace/pipeline-workspace.jsx, src/components/pipeline/pipeline.jsx, src/components/stage-builder-toolbar/stage-builder-toolbar.jsx, src/components/stage-builder-toolbar/stage-builder-toolbar.spec.js, src/components/stage-operator-select/stage-operator-select.jsx, src/components/stage-operator-select/stage-operator-select.spec.js, src/components/stage-preview-toolbar/stage-preview-toolbar.jsx, src/components/stage-toolbar/stage-toolbar.jsx, src/components/stage-toolbar/stage-toolbar.spec.js, src/components/stage/stage.jsx, src/modules/comments.js, src/modules/comments.spec.js, src/modules/index.js, src/modules/pipeline.js, src/modules/pipeline.spec.js, src/modules/saved-pipeline.js, src/stores/store.spec.js
=> COMPASS-2857: Adding comments

src/components/pipeline-preview-toolbar/pipeline-preview-toolbar.jsx, src/components/toggle-stage/toggle-stage.jsx
=> COMPASS-2954 updated toggles in aggregation to new green

src/components/stage-editor/stage-editor.jsx, src/modules/index.js
Fix of missing first stage body after restoring pipeline.
=> Compass 2958 saved pipeline loaded with first stage missing

package-lock.json, src/stores/store.js
Needs [compass PR](https://github.com/10gen/compass/pull/1498) to be merged in first to work properly.
=> refresh input documents on data refresh

package-lock.json, package.json, src/components/input-preview/input-preview.jsx
uses updated [compass-crud](https://github.com/10gen/compass-crud/pull/84) prop in `<Document>` component to display dates in UTC.
=> use timezone prop to display docs' dates in utc

package-lock.json, package.json
updates compass-crud to pass in tz to readonly document
=> update compass crud's readonly doc props

src/components/stage-editor/stage-editor.less
=> COMPASS-3046 - Add horizontal scrolling to error message

electron/renderer/index.js, package-lock.json, package.json, src/stores/store.js, src/stores/store.spec.js
No longer needed since the store just listens for 'fields-changed' event.
=> Remove field-store as dep

package-lock.json, package.json
=> COMPASS-3410: Agg operator highlighting

package-lock.json, package.json
=> Cleanup from 3.0.0

package-lock.json, package.json
See https://github.com/mongodb-js/ace-mode/commit/01f7e0f3959cfb0807651b1a364b820051514c7e
=> Fix single quote field highlighting

.travis.yml, package-lock.json, package.json
Fix for `connection-model`s use of keytar. Somehow related to #81
=> Fix npm start error

package-lock.json, package.json
Parsing $objectToArray as part of the query expression
=> COMPASS-3552 Object to array in expression support

src/modules/create-view/index.js, src/modules/index.js, src/stores/create-view.js
=> Add proper debugs and fix emitting to actually create

package-lock.json, src/components/input-preview/input-preview.less, src/components/pipeline-toolbar/overview-toggler.spec.js, src/components/pipeline-toolbar/pipeline-builder-toolbar.spec.js, src/components/pipeline-toolbar/pipeline-toolbar.spec.js, src/components/stage-editor/stage-editor.spec.js, src/components/stage-workspace/stage-workspace.spec.js, src/stores/create-view.spec.js
=> COMPASS-3646: Fix dropdown menu being hidden

package-lock.json, package.json
Bringing updates from [stage-validator lib](queries need to have access to agg_array expressions)
=> COMPASS-3605: allow query_expressions to have agg_array expressions

package-lock.json, src/components/aggregations/aggregations.jsx, src/components/pipeline-toolbar/pipeline-builder-toolbar.jsx, src/components/pipeline-toolbar/pipeline-builder-toolbar.spec.js, src/components/pipeline-toolbar/pipeline-toolbar.jsx, src/components/pipeline-toolbar/pipeline-toolbar.spec.js, src/components/pipeline/modals/confirm-new-pipeline.jsx, src/components/pipeline/modals/confirm-new-pipeline.less, src/components/pipeline/modals/confirm-new-pipeline.spec.js, src/components/pipeline/pipeline.jsx, src/components/stage-preview-toolbar/stage-preview-toolbar.spec.js, src/components/stage-preview/stage-preview.spec.js, src/components/stage-workspace/stage-workspace.spec.js, src/modules/index.js, src/modules/is-new-pipeline-confirm.js, src/modules/is-new-pipeline-confirm.spec.js, src/stores/store.spec.js
- Tests clean up.
- Show a confirmation modal before creating a new pipeline.
=> COMPASS-3940 is new pipeline confirm

README.md
Updates readme with information about events emitted and received from the App Registry. Also includes analytics events logged.
=> COMPASS-3961: update-readme to include emitted app registry events

package-lock.json, package.json
```
Uncaught Error: Cannot find module './functions/gte'
at n (/Users/lucas/compass-electron6/node_modules/@mongodb-js/compass-aggregations/lib/index.js:14)
at /Users/lucas/compass-electron6/node_modules/@mongodb-js/compass-aggregations/lib/index.js:6
at Object.get [as gte] (/Users/lucas/compass-electron6/node_modules/@mongodb-js/compass-aggregations/lib/index.js:6)
at t.value (/Users/lucas/compass-electron6/node_modules/@mongodb-js/compass-aggregations/lib/index.js:14)
at t.value (/Users/lucas/compass-electron6/node_modules/@mongodb-js/compass-aggregations/lib/index.js:14)
at t.value (/Users/lucas/compass-electron6/node_modules/@mongodb-js/compass-aggregations/lib/index.js:14)
at finishClassComponent (/Users/lucas/compass-electron6/node_modules/react-dom/cjs/react-dom.development.js:18470 …
```
=> fix: semver@7 does not work with webpack

electron/renderer/index.js, package-lock.json, package.json, src/components/pipeline-workspace/custom-drag-layer.jsx, src/components/pipeline-workspace/custom-drag-layer.less, src/components/pipeline-workspace/sortable-stage-container.jsx, src/components/pipeline-workspace/sortable-stage-container.less, src/components/pipeline-workspace/sortable-stage-list.jsx
Changes the drag overlay to a custom one for stages, since Chrome cannot calculate the drag layer and location properly. Suggestions of creating a stacking context on each element or executing a transform cause Chrome to render only the stage, but the positioning of the overlay still factors in the entire page.
=> COMPASS-4152: Use custom drag & drop layers

src/constants.js
As we are changing `$searchBeta` to `$search`, this PR updates the configuration for the one-liner and docs link so they are inserted correctly when the stage is selected in the drop-down.
=> Updated `$search` one liner and docs link

package-lock.json, package.json
=> COMPASS-4369: fix storage-mixin:find response callback called twice

package-lock.json, package.json
=> $out and $sql not shown when connected to a data lake

scripts/download-akzidenz.js
=> fix: font file extension naming

src/constants.js, src/modules/max-time-ms.spec.js
Increase max time ms to 1 minute by default
Part of https://jira.mongodb.org/browse/COMPASS-4530
=> feat(COMPASS-4530): Increase max time ms to 1 minute

package-lock.json, package.json
Fixes 
```bash
> npm install                                                                         
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/mongodb-js-precommit/pre-commit@github:mongodb-js/pre-commit" as it does not contain a package.json file.
```
=> Bump precommit to fix install issue
