- src/assets/less/compass/variables/_palette.less
Updated `palette.less` greens, so `.pipeline-preview-toolbar-indicator` will use `@green2`: `#13AA52`
Note: Colors to be updated **by MongoDB World**
> COMPASS-2914 updated green status indicator

- src/components/stage-editor/stage-editor.jsx
Increase the debounce on the pipeline running from 500ms to 750ms for the slower typers.
> COMPASS-2932 Increase Agg Pipeline debounce to 750ms

- package-lock.json
- src/components/stage-editor/stage-editor.less
- src/components/stage-preview/stage-preview.less
- src/components/stage-workspace/stage-workspace.less
@durran This should allow documents in preview area to expand to parent's full height when code editor height has been increased:
Might be nice if the document height only increased if it needed to in order to accommodate fields not shown... but I think this does the job of at least allowing the height to match the code editor height which prevents a bad experience for those cases with document results with large number of fields.
cc @sampoonachot
> COMPASS-2929 - Increase Document Height Dynamically with Expression Editor Height

- src/components/save-pipeline-card/save-pipeline-card.less
The name now wraps before the buttons start:
Or, if not moused over,
> COMPASS-3049 - Cannot see buttons with really long saved pipeline

- src/components/stage-editor/stage-editor.less
> COMPASS-3297: Fix long error messages being hidden

- .gitignore
- src/components/aggregations/aggregations.jsx
- src/components/input/input.jsx
- src/components/stage-editor/stage-editor.jsx
- src/modules/index.js
- src/modules/index.spec.js
- src/modules/is-overview-on.js
- src/modules/is-overview-on.spec.js
- src/stores/store.spec.js
combineReducers expects that a reducer exists for each part of the state
it operates on, otherwise it console.errors that a key is in the state
that it doesn't know about. Also without a module listed in
combineReducers the initial state of the store is set up with any extra
state as undefined. This causes prop validation errors when initialising
the component as isOverviewOn is undefined at that point.
The later could be fixed by setting a default in the aggregations
component but does not solve the first annoying issue. This is an
in-between solution that allows isOverviewOn to continue handling the
toggle event in the root module, while allowing for the is-overview-on
module to hold the action creator and the reducer that sets up the
initial state.
> Split overview modules for combineReducers:

- src/components/input-preview-toolbar/input-preview-toolbar.less
- src/components/pipeline-builder-toolbar/collation-collapser.less
- src/components/pipeline-builder-toolbar/pipeline-builder-toolbar.less
- src/components/pipeline-preview-toolbar/pipeline-preview-toolbar.less
- src/components/pipeline/collation-toolbar.less
- src/components/stage-preview-toolbar/stage-preview-toolbar.less
- src/components/stage-preview/stage-preview.less
> Fix text overflow

- examples/stage-editor.stories.js
- field-store/example.js
- field-store/index.js
- field-store/package.json
- src/modules/stage.js
- src/modules/stage.spec.js
Fixes: [COMPASS-2888](https://jira.mongodb.org/browse/COMPASS-2888)
1. Should projections that drop a field say `{_id: 0}` not show up in subsequent stage autocompletes?
> Only if 100% accurate which could be tricky.
2. Should projection autocomplete entries include the underlying type? Would be best effort like `price=type<Int>` ➡️ `avg_price: {$avg: "$price"}` ➡️ `avg_price=type<Int>`
> We don't expose types from FieldStore in mongodb-js/ace-autocompleter, so that would need to come first.
3. Should we support other operators that create projection? Take at look at the below + est complexity (ht @mmarcon)
* `$project`
* `$addFields`
* `$bucket`
* `$bucketAuto`
* `$count`
* `$facet`
* `$graphLookup`
* `$group`
* `$lookup`
* `$replaceRoot`
* `$unwind`
* `$collStats` //Happy to ignore this …
> COMPASS-2888: Autocompletion includes projections

- electron/renderer/index.js
Fixes buttons and other globals set from `10gen/compass` to correctly apply in electron via `npm start`. `less/global.less` properly monkeys around bootstrap, font-awesome, etc. so it can be a black box going forward for any future refactoring. No change needed for storybook as it already has this.
> Use new global.less in electron harness

- src/components/aggregations/aggregations.jsx
- src/components/pipeline-workspace/pipeline-workspace.jsx
- src/components/pipeline/pipeline.jsx
- src/components/stage-editor/stage-editor.jsx
- src/components/stage-workspace/stage-workspace.jsx
- src/components/stage/stage.jsx
- src/modules/index.js
When <StageEditor /> is empty and you paste an aggregation pipeline as text, automatically populate the workspace with the complete text.
Also handles pasted pipelines with more than one stage:
> COMPASS-3086: Paste pipeline into empty stage to import

- examples/README.md
- examples/aggregations.stories.js
- examples/example-pearsons-rho.js
A real-world analytics case from @johnlpage that calculates [the correlation co-efficient of two fields using Pearsons Rho](http://ilearnasigoalong.blogspot.com/2017/10/calculating-correlation-inside-mongodb.html).
Data added to the Compass free-tier Atlas w/ Stitch public read rules.
> Add Pearson's rho example from @johnlpage

- src/components/stage-editor/stage-editor.jsx
`onChange()` was double prop'd oddly not generating errors or breaking things else. This caused the redux action creators in `onStageChange()` not to be called.
> Fix stage changes not running auto-preview

- .eslintrc
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration
> Fix Warning: React version not specified

- src/modules/index.js
> Fix emit open-create-view

- package-lock.json
- package.json
- src/components/stage-builder-toolbar/stage-builder-toolbar.jsx
- src/components/stage-preview-toolbar/stage-preview-toolbar.jsx
- src/components/stage-preview-toolbar/stage-preview-toolbar.less
- src/components/stage-preview-toolbar/stage-preview-toolbar.spec.js
- src/components/stage-toolbar/stage-toolbar.jsx
- src/constants.js
With this PR we tweak the design of the stage builder so the info sprinkle is moved next to the stage name in the preview area and contains a tooltip that explains in short what the stage does.
~Unit tests are not updated yet.~
> New design for agg builder sprinkles

- src/assets/less/compass/variables/_palette.less
- src/components/stage-builder-toolbar/stage-builder-toolbar.jsx
- src/components/stage-editor/stage-editor.less
- src/components/stage-preview-toolbar/stage-preview-toolbar.jsx
- src/components/stage-preview-toolbar/stage-preview-toolbar.spec.js
- src/components/stage-toolbar/stage-toolbar.less
- src/components/stage/stage.less
- src/constants.js
1. Updated color palette for error banners:
2. Added 1-liner for $merge and $searchBeta
> COMPASS-3882 Added 1-liners and updated error banners

- package-lock.json
- package.json
- src/components/stage-preview-toolbar/stage-preview-toolbar.jsx
- src/components/stage-preview-toolbar/stage-preview-toolbar.spec.js
While we constrain users to the stages in the dropdown with 'Create pipeline from text' they are still able to import pipelines with stages that are invalid. From analytics, it looks like they actually do that sometimes. We want to make sure that when they do, Compass does not completely break.
> Compass 3950: Aggregation tab blanks out when importing a pipeline with an invalid stage

- src/modules/pipeline.js
- src/modules/pipeline.spec.js
The issue described in the ticket https://jira.mongodb.org/browse/COMPASS-4263 happens because of using the `out` operator on the large collection. For aggregations, without `out` we execute pipelines not on the whole collection, but on the subset because of UI performance issues (we can not display so many results in the preview, and it takes a long time to get these results). So we check if the pipeline itself has a limit stage and if not we use a default value for the `limit` operator.
For pipelines with `out` we do not add the `limit` operator as the last stage of the pipeline, because according to design `out` should be the last stage of the pipeline. This exactly what was causing the issue, because the pipeline was running on the whole collection and Compass UI got frozen.
To solve …
> COMPASS-4263: fix freezing UI with out operator

- src/components/stage-preview-toolbar/stage-preview-toolbar.jsx
- src/components/stage-preview-toolbar/stage-preview-toolbar.spec.js
- src/modules/pipeline.js
COMPASS-4368
This PR adds a check around showing the output destination for an out stage. Currently because we rate limit the running and parsing of the stage's input value, there's a chance the input is not valid, while the `isValid` boolean is still true because it has not yet been run. In those situations we know 
I think if we want to add a bit more complexity but be a bit more solid on this going forward we could add a new variable stored on stages which maintains whether the stage has been checked for validity yet on its current input. In which cases we could be a bit cleaner here. Opted for the smaller footprint PR. If the reviewer thinks this would be better I'm totally down to do the fix, will take a bit longer though.
To test the original crashing behavior, having three quotes …
> COMPASS-4368: Fix error on invalid, not yet run out stage 

- package-lock.json
- package.json
Pulls in https://github.com/mongodb-js/query-parser/commit/46f84f666f4731669d03449b86b0b648ebff4699
Since this package has `mongodb-query-parser` as a peer & dev dependency this change is more for the development in this package.
> COMPASS-4355: Update mongodb-query-parser to bring in int64 fix for dev

- src/components/stage-builder-toolbar/select-option-with-tooltip/select-option-with-tooltip.jsx
- src/components/stage-builder-toolbar/select-option-with-tooltip/select-option-with-tooltip.less
- src/components/stage-builder-toolbar/select-option-with-tooltip/select-option-with-tooltip.spec.js
- src/components/stage-builder-toolbar/stage-operator-select.jsx
This PR adds a tooltip to the stage operator options in the stage select dropdown.
The descriptions are from https://github.com/mongodb-js/ace-autocompleter/blob/master/lib/constants/stage-operators.js
> feat: Add tooltip to stage operator select with stage description

- src/modules/extract-stages.js
- src/modules/extract-stages.spec.js
Fixes stage names being undefined when defined using quotes.
To add support for $function we switched to a less “smart” parser that does not validate stages.
The new js parser represents object properties in different way depending or not they have quotes (https://github.com/estree/estree/blob/master/es5.md#property). 
- if an object property has quotes the parser internally thinks that is a regular string (Literal),
- if it doesn’t it treats it like a variable (Identifier).
Here we handle both cases.
> fix: stage names undefined with quotes

- src/components/stage-preview/stage-preview.jsx
- src/components/stage-preview/stage-preview.less
- src/components/stage-preview/stage-preview.spec.js
> fix: hide empty state when loading
